# NumPy

## Linear Algebra Library for Python

### Install Python using Anaconda Distribution to make sure all underlaying dependencies (such as Linear Algebra libraries) all sink up with the use of a conda install.

### In Anaconda, install NumPy by going to command prompt and typing 

## conda install numpy    

## pip install numpy

# NumPy arrays

### Numpy arrays essentially come in two flavours: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (note:a matrix can still have only one row or one column).

In [10]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [11]:
import numpy as np

In [12]:
arr = np.array(my_list)

In [13]:
arr

array([1, 2, 3])

### if we want to get two dimentional arrays

In [14]:
my_data = [[1,2,3],[4,5,6],[7,8,9]]

In [26]:
np.array(my_data)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### The most common way to build an array is using built in arrange() function, then pass in start, stop and step sizes in the argument. This is very useful to generate arrays using NumPy

### Return evenly spaced values within a given interval.

In [27]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [29]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [30]:
np.arange(0,10, 5)

array([0, 5])

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace    
The numpy.linspace () function returns number spaces evenly 

In [35]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [36]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### numpy.identity

### numpy.identity(n, dtype=None, *, like=None) |Return the identity array | The identity array is a square array with ones on the main diagonal | Creates an identity matrix

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random
Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [39]:
np.random.rand(2)

array([0.39393618, 0.11268625])

In [40]:
np.random.rand(5,5)

array([[0.96367564, 0.47075981, 0.07399934, 0.9080397 , 0.30696686],
       [0.10050814, 0.25137392, 0.9836433 , 0.40753337, 0.75076895],
       [0.49197917, 0.97646407, 0.13836144, 0.2153467 , 0.40348156],
       [0.35424704, 0.49653622, 0.10052893, 0.78747896, 0.2068465 ],
       [0.76939561, 0.34376124, 0.79621975, 0.14696595, 0.96791621]])

### randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [41]:
np.random.randn(2)

array([0.13855452, 1.1722249 ])

In [42]:
np.random.randn(5,5)

array([[ 1.1342696 ,  0.42347223, -1.34920335,  2.12139955,  1.70168598],
       [ 0.9659134 ,  0.18763581,  0.47639974, -1.1360312 , -0.82896482],
       [-1.57192301, -0.37486092, -0.05022172,  2.1737168 , -0.14041058],
       [-1.65011892, -0.04875378, -2.01034357, -0.08070374, -0.66812467],
       [-1.48122219,  0.4817603 ,  0.46709437,  1.93582035, -0.35226259]])

### randint
Return random integers from low (inclusive) to high (exclusive).

In [44]:
np.random.randint(1,100)

78

In [45]:
np.random.randint(1,100,10)

array([31, 96, 92, 28, 34, 78, 80, 23, 72, 52])

## Array Attributes and Methods

In [46]:
arr= np.arange(25)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
np.random.randint(1,100,10)

array([63, 87, 74, 44, 49, 84, 96, 77, 73, 86])

In [49]:
arr =np.arange(25)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
ranarr = np.random.randint(0, 50, 10)

In [53]:
ranarr

array([ 5, 48,  0, 18, 17,  2, 24, 47, 44,  9])

## Reshape
Returns an array containing the same data with a new shape.

In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

argmin() returns the index of a minimum value
argmax() returns the index of a maximum value

In [55]:
ranarr

array([ 5, 48,  0, 18, 17,  2, 24, 47, 44,  9])

In [57]:
ranarr.max()

48

In [61]:
ranarr.min()

0

In [58]:
ranarr.argmin()

2

In [60]:
ranarr.argmax()

1

## Shape
Shape is an attribute that arrays have (not a method):

In [62]:
arr = arr.reshape(5,5)

In [63]:
arr.shape

(5, 5)

In [64]:
arr.dtype

dtype('int32')

In [65]:
arr.shape

(5, 5)

In [66]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [68]:
arr.reshape(25,1).shape

(25, 1)

In [69]:
arr.dtype

dtype('int32')

## NumPy Indexing and Selection

In [70]:
#Creating sample array
arr = np.arange(0,11)

In [71]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [72]:
arr[8]


8

In [73]:
arr[1:5]

array([1, 2, 3, 4])

## Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [74]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [75]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [77]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [79]:
arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [80]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### In sclice method a change occur in original array. and with copy() the original array is not changed

### Indexing a 2D array (matrices)
The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [84]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [85]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [86]:
# Getting individual element value
arr_2d[1,0]

20

In [87]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [88]:
arr_2d[2]

array([35, 40, 45])

In [93]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [94]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [97]:
arr = np.arange(1,11)

In [98]:
arr> 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [99]:
bool_arr = arr>5

In [100]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [103]:
arr[bool_arr] #only returns true boolean value

array([ 6,  7,  8,  9, 10])

In [104]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [105]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

## Fancy Indexing
Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:P

In [106]:
arr_2d = np.arange(50).reshape(5,10)

In [107]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [108]:
arr_2d[1:3,]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [110]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Numpy basic operations

###### Arithmetic

In [112]:
arr = np.arange(0,10)

In [113]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [114]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [115]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [116]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\upama\AppData\Local\Temp\ipykernel_440\2878212635.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [117]:
# Also warning, but not an error instead infinity
1/arr


C:\Users\upama\AppData\Local\Temp\ipykernel_440\1953009274.py:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [118]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions
Numpy comes with many universal array functions, which are essentially just mathematical operations you can use to perform the operation across the array.

In [120]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
#Calcualting exponential (e^)
np.exp(arr)

In [121]:
np.max(arr) #same as arr.max()


9

In [122]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

## NumPy Exercises

### Import NumPy as np

In [123]:
import numpy as np

### Create an array of 10 zeros

In [124]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Create an array of 10 ones

In [125]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Create an array of 10 fives

In [128]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### Create an array of the integers from 10 to 50

In [127]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

### Create an array of all the even integers from 10 to 50

In [129]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

### Create a 3x3 matrix with values ranging from 0 to 8

In [131]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Create a 3x3 identity matrix

In [132]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Use NumPy to generate a random number between 0 and 1

In [137]:
np.random.rand(1)

array([0.17056797])

### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [139]:
np.random.randn(25)

array([-1.94984423,  3.29022722, -0.44574323, -0.66917633, -0.50067855,
       -1.00135571, -0.76271934, -1.84524487,  1.00364958,  1.37387459,
        0.89869073, -0.87312414,  1.33201619,  0.10517809, -1.7881932 ,
       -0.41407623,  0.32408154, -0.50525685, -1.57786583, -0.53286723,
       -0.10915627,  0.99495468,  0.17567597,  0.15024446, -0.09979809])

### Create the following matrix:

In [141]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

### Create an array of 20 linearly spaced points between 0 and 1:

In [143]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

In [144]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW


In [146]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [147]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW


In [149]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

### 20

In [160]:
mat[3,4]

20

In [153]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [161]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [162]:
mat[3,:]

array([16, 17, 18, 19, 20])

### Get the sum of all the values in mat

In [157]:
mat.sum()

325

### Get the standard deviation of the values in mat

In [158]:
mat.std()

7.211102550927978

### Get the sum of all the columns in mat

In [159]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])